name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
    name: Windows conan build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --user conan
          conan profile detect
          conan install . --build=missing --options=boost/1.82.0:shared=True
      - name: Build python wheel and install it
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW ..
          cmake --build . --config Release
          ctest --output-on-failure -C Release
