name: Conan ninja build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Windows conan build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install dependencies
        run: |
          python -m pip install --user conan
          conan profile detect
          conan install . --build=missing --options=boost/1.82.0:shared=True
      # cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=D:\a\play_with_conan\play_with_conan\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
      - name: Build python wheel and install it
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_TOOLCHAIN_FILE="D:\a\play_with_conan\play_with_conan\build\generators\conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091=NEW ..
          ninja
          ninja test
